## https://github.com/arduino/Arduino/issues/2596

sudo: false
language: java

jdk:
- openjdk6

script:
- git clone https://github.com/igrr/Arduino.git --branch esp8266 --single-branch
- cd Arduino/build
- sed -i -e "s|d2ae7aa8a3bb8639e3b1d2a7f6b764e274b25d3f|e8c6df47299348a0233e18647e2ed93c8afe65c2|g" esptool-0.0.3.tgz.sha
- ant clean build
- echo "" | ant dist
- ls -lh ./linux/arduino-*.tar.xz
- ls /usr/lib/jvm/

deploy:
  provider: releases
  api_key:
    secure: iKoz+XGSeBxHTbPWdygLwb49ucEMofrQci4LYrT+BoJ5tIAsKl7YB8AdzQQAVU7YYD6gN1f7002aRSk8WBhEFUmSCeHK/70d52g7hXrN01o1vYQkKvNY8Ts1jS3KYYytfqxG7HuunuVI+v1C3j1QjKKAXZa3oZVqmk4znrTuZXU=
  skip_cleanup: true
  file_glob: true
  file: '$TRAVIS_BUILD_DIR/Arduino/build/linux/arduino-*.tar.xz'
  on:
    tags: true
    all_branches: true
