## https://github.com/arduino/Arduino/issues/2596

sudo: false
language: java

jdk:
- openjdk6

before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"

script:
- git clone https://github.com/igrr/Arduino.git
- cd Arduino/build
- ant clean build
- find .
