## https://github.com/arduino/Arduino/issues/2596

sudo: true
language: java

jdk:
- openjdk6

script:
- sudo apt-get update -qq
- sudo apt-get install -qq autoconf gperf bison flex texinfo libtool libncurses5-dev gawk python-serial libexpat-dev xorriso imagemagick
- git clone https://github.com/igrr/Arduino.git --branch esp8266 --single-branch
- cd Arduino/build
- sed -i -e "s|d2ae7aa8a3bb8639e3b1d2a7f6b764e274b25d3f|e8c6df47299348a0233e18647e2ed93c8afe65c2|g" esptool-0.0.3.tgz.sha
- ant clean build
- echo "" | ant dist
- ls -lh $TRAVIS_BUILD_DIR/Arduino/build/linux/arduino-*.tar.xz
- cd $TRAVIS_BUILD_DIR
- git clone -b lx106 git://github.com/jcmvbkbc/crosstool-NG.git 
- cd crosstool-NG
- echo $LD_LIBRARY_PATH
- unset LD_LIBRARY_PATH
- ./bootstrap && ./configure --prefix=`pwd` && make && make install
- ./ct-ng xtensa-lx106-elf
- ./ct-ng build
- cd ./builds
- tar czf $TRAVIS_BUILD_DIR/linux64-xtensa-lx106-elf.tgz xtensa-lx106-elf/
- ls -lh $TRAVIS_BUILD_DIR/linux64-xtensa-lx106-elf.tgz
- cd $TRAVIS_BUILD_DIR
- bash -x $TRAVIS_BUILD_DIR/generate-appimage

deploy:
  provider: releases
  api_key:
    secure: iKoz+XGSeBxHTbPWdygLwb49ucEMofrQci4LYrT+BoJ5tIAsKl7YB8AdzQQAVU7YYD6gN1f7002aRSk8WBhEFUmSCeHK/70d52g7hXrN01o1vYQkKvNY8Ts1jS3KYYytfqxG7HuunuVI+v1C3j1QjKKAXZa3oZVqmk4znrTuZXU=
  skip_cleanup: true
  file_glob: true
  file: 
    - '$TRAVIS_BUILD_DIR/Arduino/build/linux/arduino-*.tar.xz'
    - '$TRAVIS_BUILD_DIR/linux64-xtensa-lx106-elf.tgz'
    - '$TRAVIS_BUILD_DIR/Arduino.AppImage'
  on:
    tags: true
    all_branches: true
