## https://github.com/arduino/Arduino/issues/2596

sudo: false
language: java

jdk:
- openjdk6

script:
- git clone https://github.com/igrr/Arduino.git
- cd Arduino/build
- ant clean build
- echo "" | ant dist
- find .
