#!/bin/bash

#
# Generate an AppImage using the build artefacts created with travis
#

# Be verbose
env

# Generate AppDir
mkdir -p $TRAVIS_BUILD_DIR/bundle
cd $TRAVIS_BUILD_DIR/bundle
ls -lh $TRAVIS_BUILD_DIR/Arduino/build/linux/arduino-*.tar.xz
tar xvJf $TRAVIS_BUILD_DIR/Arduino/build/linux/arduino-*.tar.xz
ls -lh
mv arduino-* Arduino.AppDir
ls -lh
mkdir -p ./tmp
cd ./tmp
jre=$(sudo apt-get -y install openjdk-7-jre --print-uris | cut -d " " -f 1 | grep jre | sed -e "s/'//g")
wget $jre
find *.deb -exec dpkg -x {} . \;
cd $TRAVIS_BUILD_DIR/bundle
mv tmp/usr/lib/jvm/java-1.7.0-openjdk-amd64/jre/ Arduino.AppDir/java

# Generate icon
cd Arduino.AppDir/
convert lib/arduino_icon.ico -resize 48x48 tmp.png
mv tmp-10.png arduino.png
rm tmp*png

# Generate desktop file
cat > arduino.desktop <<\EOF
[Desktop Entry]
Name=Arduino
Type=Application
Icon=arduino.png
Exec=AppRun
EOF

cd $TRAVIS_BUILD_DIR/bundle

# Get and unpack AppImageAssistant
# sudo apt-get install -qq xorriso imagemagick
wget "https://github.com/probonopd/AppImageKit/releases/download/1/AppImageAssistant"
xorriso -indev AppImageAssistant -osirrox on -extract / aia

# Generate AppImage from the AppDir
./aia/package ./Arduino.AppDir ./Arduino.AppImage
mv ./Arduino.AppImage $TRAVIS_BUILD_DIR/
ls -lh $TRAVIS_BUILD_DIR/Arduino.AppImage
