#!/bin/bash

#
# Generate an AppImage using the build artefacts created with travis-ci
# For more information, see https://github.com/probonopd/AppImageKit
#

# Be verbose
env

# Generate AppDir
mkdir -p $TRAVIS_BUILD_DIR/bundle
cd $TRAVIS_BUILD_DIR/bundle
tar xJf $TRAVIS_BUILD_DIR/Arduino/build/linux/arduino-*.tar.xz
mv arduino-* Arduino.AppDir
mv Arduino.AppDir/arduino Arduino.AppDir/AppRun
mkdir -p ./tmp
cd ./tmp
jre=$(sudo apt-get -y install openjdk-7-jre --print-uris | cut -d " " -f 1 | grep jre | sed -e "s/'//g")
wget $jre
find *.deb -exec dpkg -x {} . \;
cd $TRAVIS_BUILD_DIR/bundle
mv tmp/usr/lib/jvm/java-1.7.0-openjdk-amd64/jre/ Arduino.AppDir/java

# Add esp8266 toolchain and esptool
mkdir -p Arduino.AppDir/hardware/tools/esp8266/
cd Arduino.AppDir/hardware/tools/esp8266/
tar xzf $TRAVIS_BUILD_DIR/linux64-xtensa-lx106-elf.tgz .
mkdir -p esptool-0.0.3/
cd esptool-0.0.3/
cp $TRAVIS_BUILD_DIR/esptool-ck/esptool esptool_linux64
ln -s esptool_linux64 esptool
cd $TRAVIS_BUILD_DIR/bundle/

# Generate icon
cp $TRAVIS_BUILD_DIR/arduino.png Arduino.AppDir/

# Generate desktop file
cat > Arduino.AppDir/arduino.desktop <<\EOF
[Desktop Entry]
Name=Arduino
Type=Application
Icon=arduino.png
Exec=AppRun
EOF

# Get and unpack AppImageAssistant
# sudo apt-get install -qq xorriso
wget "https://github.com/probonopd/AppImageKit/releases/download/1/AppImageAssistant"
xorriso -indev AppImageAssistant -osirrox on -extract / aia

# Generate AppImage from the AppDir
./aia/package ./Arduino.AppDir ./Arduino.AppImage
mv ./Arduino.AppImage $TRAVIS_BUILD_DIR/
ls -lh $TRAVIS_BUILD_DIR/Arduino.AppImage
